### ISSUE TITLE
Navigate through history

### ISSUE THREAD

**Issue by slideclimb** [FirstTimeInForever/intellij-pdf-viewer#23] opened 2021-03-20 08:46 UTC
When clicking on a link or jumping to a search result, it would be nice if you could go back to where you were before following the link, by pressing some shortcut or clicking a button in the toolbar. 

History is implemented in pdfjs (https://github.com/mozilla/pdf.js/pull/2921) but I haven't checked if it is accessible in [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer).

**Comment by FirstTimeInForever** [comment] 2021-03-25 16:01
I am currently working on rewriting the browser code in Kotlin and migrating to a custom build of PDF.js, so this will be implemented when the new version will be ready.

**Comment by slideclimb** [comment] 2021-04-27 06:30
> I am currently working on rewriting the browser code in Kotlin and migrating to a custom build of PDF.js

What's the status on this? Is there anything I can do to help? I was thinking about working on the PDF viewer (resolving issues, adding minor things that I came across while using it in combination with TeXiFy) but I feel like things will be a lot easier once this refactor is done. Both in terms of maintenance and resolving merge conflicts/porting changes to Kotlin later.

So if there is anything I can do, please let me know and I will be more than happy to help :)

**Comment by FirstTimeInForever** [comment] 2021-05-05 02:36
@slideclimb I am sorry for such a long silence from me - I had a lot of stuff to do. So, the main work on the refactor is done - most of the features are working now. I also added an implementation of structure view, as many people have asked me for it.

Currently, the broken features are: 
* Presentation mode (it is completely broken as it requires a lot of work on the IDE side to support it)
* Document info
* Error reporting from browser

I'm glad that you want to help - it means a lot to me :) If you want to do something, you can take a look at the `kotlinjs-migrate` branch - I think there will be no major changes to the current code, so you can safely use it. There will be only minor changes to the `master` branch migration branch is not merged. 

Even with some of the useful stuff broken, I am thinking of releasing an alpha version of the plugin in its current state, just for testing purposes.

**Comment by slideclimb** [comment] 2021-05-05 05:32
@FirstTimeInForever No worries! That sounds pretty good already. I will definitely have a look at that branch, and I'll actually use it to see if anything else is broken. Releasing an alpha is a good idea, I'm pretty sure @PHPirates would use that as well.

You'll hear from me if I think I can be useful to fix any of the broken things, or if I decide to work on anything else. Anyways, I'm so excited that you're migrating this to Kotlin JS, so thank you for going through the hassle that comes with such a big refactor :)

**Comment by FirstTimeInForever** [comment] 2021-05-25 21:16
> @FirstTimeInForever If I `runIde` on [4b972f4](https://github.com/FirstTimeInForever/intellij-pdf-viewer/commit/4b972f4970883eefef1d271b2295f0a6f4d9efc0) (on Windows) then I get `java.io.FileNotFoundException: Could not load resource file: \\web-view\index.html\`, is that work in progress or am I missing something?
> 
> ```
> java.io.FileNotFoundException: Could not load resource file: \\web-view\index.html\
> 	at com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader.loadFromRoot(PdfResourceLoader.kt:37)
> 	at com.firsttimeinforever.intellij.pdf.viewer.jcef.PdfStaticServer.sendInternalFile(PdfStaticServer.kt:79)
> 	at com.firsttimeinforever.intellij.pdf.viewer.jcef.PdfStaticServer.process(PdfStaticServer.kt:46)
> 	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:21)
> 	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:35)
> 	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:16)
> 	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:46)
> 	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
> 	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:46)
> 	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:50)
> 	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
> 	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
> 	at org.jetb
> ```

This is definitely a bug. I'll try to fix it as soon as possible.

**Comment by FirstTimeInForever** [comment] 2021-05-27 19:40
@PHPirates pathing issue should be fixed by `f92f341d1c612f8736b9e7ff610993ea302c4c3e`.

**Comment by PHPirates** [comment] 2021-05-28 07:38
I can confirm it fixed, thanks!

**Comment by PHPirates** [comment] 2021-06-13 07:51
Is this history navigation supposed to work when clicking a link which goes to a page on the internet? The Go Back button isn't doing anything for me. (0.12.0-alpha.4) It works when staying within the pdf for browsing between pages, but the problem is that when I click on an Internet link the only way to go back is to close the pdf and open it again.

**Comment by PHPirates** [comment] 2023-05-03 17:15
Fixed in 0.12

**Closed by PHPirates** 2023-05-03 17:15 UTC
Labels: Should be fixed in 0.12.0
