### ISSUE TITLE
Inverse search causes PyCharm freeze

### ISSUE THREAD

**Issue by kalekje** [FirstTimeInForever/intellij-pdf-viewer#34] opened 2021-06-03 15:12 UTC
As title states. One CTRL+Click in the PDF causes Pycharm to freeze. I'm unsure if this issue is on my end or not.

**Comment by PHPirates** [comment] 2021-06-03 15:57
#32 Try the alpha build.

**Comment by PHPirates** [comment] 2023-05-03 17:54
Duplicate of #32, fixed already.

**Closed by PHPirates** 2023-05-03 17:54 UTC
