### ISSUE TITLE
Does the plugin support the Pycharm platform?

### ISSUE THREAD

**Issue by noneaddress** [FirstTimeInForever/intellij-pdf-viewer#40] opened 2021-08-10 15:03 UTC
## My Questions
According to the README file of the [**TEXiFy**,](https://github.com/Hannah-Sten/TeXiFy-IDEA) it seems that I can preview the PDF version of my tex file after installing the **PDF Viewer**. 
But I can not find the plugin in my marketplace. When I try install Plugin from Disk after downloading the archive, it shows that the plugin, PDF Viewer, is not compatible with my IDE.
After browsing [home page of the plugin,](https://plugins.jetbrains.com/plugin/14494-pdf-viewer), I found that the plugin supports all IntelliJ-based IDEs, which upsets me a lot.
## The version of my Software and Plugin
Pycharm 2020.1
TexiFy 0.6.10
PDF Viewer(archive) 0.11.1 & 0.10.2
## Operating System
Windows 10
Thank you for answering my question. I am just a beginner, please forgive me for my ignorance.......

**Comment by PHPirates** [comment] 2021-08-10 18:05
Duplicate of Hannah-Sten/TeXiFy-IDEA#2024, in summary: update PyCharm to 2020.2 or later.

**Closed** 2023-05-03 17:51 UTC
