### ISSUE TITLE
background  color

### ISSUE THREAD

**Issue by xsharh** [FirstTimeInForever/intellij-pdf-viewer#39] opened 2021-08-04 14:08 UTC
hope it can change the page background color,

**Comment by cenktaskin** [comment] 2022-06-29 10:24
> hope it can change the page background color,

https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/10

Looks like there is an experimental feature but I couldn't get it working.

**Comment by PHPirates** [comment] 2023-05-03 17:56
Duplicate of #10, will be fixed in the next version

**Closed by PHPirates** 2023-05-03 17:56 UTC
