### ISSUE TITLE
input goes to wrong tab

### ISSUE THREAD

**Issue by jlous** [FirstTimeInForever/intellij-pdf-viewer#59] opened 2022-11-10 08:09 UTC
If I have more than one pdf tab open, any toolbar command (e.g. zoom, rotate), in _any_ of the tabs, affect the content of _only the first_ tab opened.

0.14.0

**Comment by Mattwmaster58** [comment] 2023-01-31 02:37
wouldn't be surprised if this was related to #56

**Comment by big-mak** [comment] 2023-04-13 12:58
duplicate of #55

**Closed** 2023-05-03 17:20 UTC
